#!groovy

/**
 *	Copyright (c) 2017 SAP SE or an SAP affiliate company.  All rights reserved.
 *
 *	This software is the confidential and proprietary information of SAP
 *	("Confidential Information"). You shall not disclose such Confidential
 *	Information and shall use it only in accordance with the terms of the
 *	license agreement you entered into with SAP.
*/

@Library('jenkins-library-alejandra@newConfig') _

node() {

  stage("Clone sources and setup environment"){
    deleteDir()
    checkout scm
    setupCommonPipelineEnvironment script: this
  }

  stage("Build Fiori App"){
    MTAR_FILE_PATH = mtaBuild script: this
  }
  
  stage("Deploy Fiori App"){
    neoDeploy script: this, archivePath: MTAR_FILE_PATH
  }
}