#!groovy

/**
 *	Copyright (c) 2017 SAP SE or an SAP affiliate company.  All rights reserved.
 *
 *	This software is the confidential and proprietary information of SAP
 *	("Confidential Information"). You shall not disclose such Confidential
 *	Information and shall use it only in accordance with the terms of the
 *	license agreement you entered into with SAP.
*/

@Library('jenkins-library-alejandra@environmentValidation') _

node() {

  APP_PATH = 'src'
  SRC = "${WORKSPACE}/${APP_PATH}"

  stage("Clone sources and setup environment"){
    deleteDir()
    dir(APP_PATH) {
      checkout scm
      setupCommonPipelineEnvironment script: this
    }
  }

  stage("Validate installations"){
    echo '[INFO] Validating installation requirements.'
    toolValidate tool: 'java'
    toolValidate tool: 'mta'
    toolValidate tool: 'neo'
    echo '[INFO] The validation was successful.'
  }

  stage("Build Fiori App"){
    MTAR_FILE_PATH = mtaBuild buildTarget: 'NEO'
  }
  
  stage("Deploy Fiori App"){
    neoDeploy script: this, archivePath: MTAR_FILE_PATH
  }
}
